// Code generated by MockGen. DO NOT EDIT.
// Source: ./payments_repository.go
//
// Generated by this command:
//
//	mockgen -source=./payments_repository.go -destination=../test/mock/mock_payments_repository.go -package mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	domain "github.com/cko-recruitment/payment-gateway-challenge-go/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockPaymentRepository is a mock of PaymentRepository interface.
type MockPaymentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentRepositoryMockRecorder
	isgomock struct{}
}

// MockPaymentRepositoryMockRecorder is the mock recorder for MockPaymentRepository.
type MockPaymentRepositoryMockRecorder struct {
	mock *MockPaymentRepository
}

// NewMockPaymentRepository creates a new mock instance.
func NewMockPaymentRepository(ctrl *gomock.Controller) *MockPaymentRepository {
	mock := &MockPaymentRepository{ctrl: ctrl}
	mock.recorder = &MockPaymentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentRepository) EXPECT() *MockPaymentRepositoryMockRecorder {
	return m.recorder
}

// AddPayment mocks base method.
func (m *MockPaymentRepository) AddPayment(payment *domain.Payment) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddPayment", payment)
}

// AddPayment indicates an expected call of AddPayment.
func (mr *MockPaymentRepositoryMockRecorder) AddPayment(payment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPayment", reflect.TypeOf((*MockPaymentRepository)(nil).AddPayment), payment)
}

// GetPayment mocks base method.
func (m *MockPaymentRepository) GetPayment(id string) *domain.Payment {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPayment", id)
	ret0, _ := ret[0].(*domain.Payment)
	return ret0
}

// GetPayment indicates an expected call of GetPayment.
func (mr *MockPaymentRepositoryMockRecorder) GetPayment(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPayment", reflect.TypeOf((*MockPaymentRepository)(nil).GetPayment), id)
}
