// Code generated by MockGen. DO NOT EDIT.
// Source: ./bank_client.go
//
// Generated by this command:
//
//	mockgen -source=./bank_client.go -destination=../test/mock/mock_bank_client.go -package mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	dto "github.com/cko-recruitment/payment-gateway-challenge-go/internal/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockBankClient is a mock of BankClient interface.
type MockBankClient struct {
	ctrl     *gomock.Controller
	recorder *MockBankClientMockRecorder
	isgomock struct{}
}

// MockBankClientMockRecorder is the mock recorder for MockBankClient.
type MockBankClientMockRecorder struct {
	mock *MockBankClient
}

// NewMockBankClient creates a new mock instance.
func NewMockBankClient(ctrl *gomock.Controller) *MockBankClient {
	mock := &MockBankClient{ctrl: ctrl}
	mock.recorder = &MockBankClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBankClient) EXPECT() *MockBankClientMockRecorder {
	return m.recorder
}

// ProcessPayment mocks base method.
func (m *MockBankClient) ProcessPayment(ctx context.Context, req *dto.BankPaymentRequest) (*dto.BankPaymentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessPayment", ctx, req)
	ret0, _ := ret[0].(*dto.BankPaymentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessPayment indicates an expected call of ProcessPayment.
func (mr *MockBankClientMockRecorder) ProcessPayment(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessPayment", reflect.TypeOf((*MockBankClient)(nil).ProcessPayment), ctx, req)
}
